// Generated by CoffeeScript 1.6.2
(function() {
  var backgroundPattern, gameTime, lastTime, now, requestAnimFrame;

  requestAnimFrame = (function() {
    return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback) {
      return window.setTimeout(callback, 1000 / 60);
    };
  })();

  gameTime = 0;

  now = null;

  lastTime = null;

  backgroundPattern = null;

  requirejs.config({
    baseUrl: 'lib/javascripts',
    paths: {
      javascripts: '../../javascripts'
    }
  }, requirejs(['jquery', 'underscore', 'javascripts/Sprite', 'javascripts/resources', 'javascripts/util', 'javascripts/Entity'], function($, _, Sprite, resources, util, Entity) {
    var canvas, ctx, init, mainLoop, player, render, reset, update, updateEntities;

    util.setup();
    ctx = util.getCanvasCtx();
    canvas = util.getCanvas();
    player = new Entity(0, 0, 0, 'down', null, null, null, null, new Sprite('assets/img/sprites.png', [0, 0], [39, 39], 16, [0, 1]));
    init = function() {
      backgroundPattern = ctx.createPattern(resources.get('assets/img/terrain.png'), 'repeat');
      reset();
      lastTime = Date.now();
      return mainLoop();
    };
    mainLoop = function() {
      var dt;

      now = Date.now();
      dt = (now - lastTime) / 1000.0;
      lastTime = now;
      update(dt);
      render();
      return requestAnimFrame(mainLoop);
    };
    reset = function() {};
    update = function(dt) {
      gameTime += dt;
      return updateEntities(dt);
    };
    render = function() {
      ctx.fillStyle = backgroundPattern;
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      return util.renderEntity(player);
    };
    updateEntities = function(dt) {
      return player.getSprite().update(dt);
    };
    return util.loadGame(['assets/img/sprites.png', 'assets/img/terrain.png'], init);
  }));

}).call(this);
