// Generated by CoffeeScript 1.6.2
(function() {
  'up, down, left, right';  define(function() {
    var Entity;

    Entity = (function() {
      function Entity(x, y, vel, dir, wSprite, lSprite, rSprite, uSprite, dSprite) {
        this.x = x;
        this.y = y;
        this.vel = vel;
        this.dir = dir;
        this.wSprite = wSprite;
        this.lSprite = lSprite;
        this.rSprite = rSprite;
        this.uSprite = uSprite;
        this.dSprite = dSprite;
        return;
      }

      Entity.prototype.getSprite = function() {
        switch (this.dir) {
          case 'left':
            return this.lSprite;
          case 'right':
            return this.rSprite;
          case 'up':
            return this.uSprite;
          case 'waiting':
            return this.wSprite;
          default:
            return this.dSprite;
        }
      };

      return Entity;

    })();
    return Entity;
  });

}).call(this);
