// Generated by CoffeeScript 1.6.2
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  (function() {
    var get, isReady, load, loading, onReady, readyCallbacks, resourceCache, _load;

    resourceCache = {};
    loading = [];
    readyCallbacks = [];
    load = function(urlOrArr) {
      if (urlOrArr instanceof Array) {
        return _.each(urlOrArr, function(url) {
          return _load(url);
        });
      } else {
        return _load(urlOrArr);
      }
    };
    _load = function(url) {
      var img;

      if (resourceCache[url]) {
        return resourceCache[url];
      } else {
        img = new Image();
        img.onload = function() {
          resourceCache[url] = img;
          if (isReady()) {
            return _.each(readyCallbacks, function(func) {
              return func();
            });
          }
        };
        resourceCache[url] = false;
        return img.src = url;
      }
    };
    get = function(url) {
      return resourceCache[url];
    };
    isReady = function() {
      var k, ready;

      ready = true;
      for (k in resourceCache) {
        if (resourceCache.hasOwnProperty(k) && !resourceCache[k]) {
          ready = false;
        }
      }
      return ready;
    };
    onReady = function(func) {
      return readyCallbacks.push(func);
    };
    return root.resources = {
      load: load,
      get: get,
      onReady: onReady,
      isReady: isReady
    };
  })();

}).call(this);
